# Generated by Django 4.2.27 on 2025-12-31 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Rule name', max_length=100)),
                ('branch_pattern', models.CharField(help_text='Branch pattern (e.g., feature/*, bugfix/*)', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('expectations', models.JSONField(default=dict, help_text='JSON object with review expectations')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['branch_pattern'],
            },
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.IntegerField(help_text='GitHub PR ID')),
                ('number', models.IntegerField(help_text='PR number in repository')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(help_text='GitHub username', max_length=255)),
                ('author_avatar', models.URLField(blank=True)),
                ('source_branch', models.CharField(help_text='Source/head branch', max_length=255)),
                ('target_branch', models.CharField(help_text='Target/base branch', max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('merged', 'Merged')], default='open', max_length=20)),
                ('github_url', models.URLField()),
                ('diff_url', models.URLField(blank=True)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('changed_files', models.IntegerField(default=0)),
                ('commits_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Repository name (e.g., owner/repo)', max_length=255)),
                ('owner', models.CharField(help_text='Repository owner/organization', max_length=255)),
                ('repo_name', models.CharField(help_text='Repository name without owner', max_length=255)),
                ('github_url', models.URLField(help_text='Full GitHub URL')),
                ('webhook_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Repositories',
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'repo_name')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('posted', 'Posted to GitHub')], default='pending', max_length=20)),
                ('overall_rating', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('needs_work', 'Needs Work'), ('poor', 'Poor')], default='good', max_length=20)),
                ('summary', models.TextField(help_text='Overall review summary')),
                ('feedback_items', models.JSONField(default=list, help_text='List of structured feedback items')),
                ('expectations_met', models.JSONField(default=dict, help_text='Which expectations were met/not met')),
                ('score', models.IntegerField(default=0, help_text='Review score out of 100')),
                ('instructor_notes', models.TextField(blank=True, help_text='Notes from instructor')),
                ('github_comment_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('branch_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='reviews.branchrule')),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.pullrequest')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_approved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('repository', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='reviews.repository')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('suggestion', 'Suggestion'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('category', models.CharField(default='general', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.review')),
            ],
            options={
                'ordering': ['file_path', 'line_number'],
            },
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='reviews.repository'),
        ),
        migrations.AddField(
            model_name='branchrule',
            name='repository',
            field=models.ForeignKey(blank=True, help_text='Specific repository (leave blank for global rule)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_rules', to='reviews.repository'),
        ),
        migrations.AlterUniqueTogether(
            name='pullrequest',
            unique_together={('repository', 'number')},
        ),
    ]
