# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='github_id',
            field=models.BigIntegerField(help_text='GitHub PR ID'),
        ),
    ]
