# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_pullrequest_github_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='github_comment_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
